image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6080
    onOpen: ignore
tasks:
  - init: pip3 install -e .
    command: >
      python3 /workspace/gym/examples/agents/cem.py &&
      python3 -m http.server 3000 -d /tmp/cem-agent-results